version: "2"

services:

  database:
    image: postgres:9.5
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: 123456
      POSTGRES_DATA: /var/lib/postgresql/data/pgdata
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    read_only: true
    volumes:
      - "database:/var/lib/postgresql/data"
    tmpfs:
      - "/tmp"
      - "/run"
    networks:
      - db-net
      - redis-net

  otree:
    # if using Docker Hub, leave "build: ./" commented out.
    # if you want to build an image locally, uncomment it.

    build: ./
    image: shinepans/otreedocker:latest
    environment:
      DATABASE_URL: "postgres://user1:123456@database/django_db"
      OTREE_ADMIN_PASSWORD: 123456
      OTREE_PRODUCTION: 1
      OTREE_AUTH_LEVEL: STUDY
    ports:
    # this is the dynamic port to set by nodejs (3099)
      - 3101:3001
    volumes:
      - "otree-resetdb:/opt/init"
      # Uncomment for live editing
      # this is for dynamic uploads for otree
      - ./:/opt/otree
    command: "otree runserver 0.0.0.0:3001"
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - db-net
      - redis-net

  redis:
    image: redis
    command: "redis-server"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    read_only: true
    networks:
      - redis-net

volumes:
  database:
  otree-resetdb:

networks:
  db-net:
  redis-net:
